version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-typescript-app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://192.168.0.129:8080/api/
      # Vous pouvez ajouter d'autres variables d'environnement icik
    restart: unless-stopped