version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attest_easy_front
    ports:
      - "3080:3080"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://192.168.0.129:8081/api/
      # Vous pouvez ajouter d'autres variables d'environnement ici
    restart: unless-stopped